2025-05-14 00:10:52,447 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2025-05-14 00:10:52,447 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Configure stats pid to 3658947
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Loading settings from /home/fdm/.config/wandb/settings
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Loading settings from /home/fdm/EVREAL/snn/wandb/settings
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'snn/wandbtest.py', 'program_abspath': '/home/fdm/EVREAL/snn/wandbtest.py', 'program': '/home/fdm/EVREAL/snn/wandbtest.py'}
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_setup.py:_flush():76] Applying login settings: {}
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_init.py:_log_setup():521] Logging user logs to /home/fdm/EVREAL/snn/wandb/run-20250514_001052-36qoy3ax/logs/debug.log
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_init.py:_log_setup():522] Logging internal logs to /home/fdm/EVREAL/snn/wandb/run-20250514_001052-36qoy3ax/logs/debug-internal.log
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_init.py:init():561] calling init triggers
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_init.py:init():611] starting backend
2025-05-14 00:10:52,448 INFO    MainThread:3658947 [wandb_init.py:init():615] setting up manager
2025-05-14 00:10:52,454 INFO    MainThread:3658947 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-14 00:10:52,455 INFO    MainThread:3658947 [wandb_init.py:init():623] backend started and connected
2025-05-14 00:10:52,459 INFO    MainThread:3658947 [wandb_init.py:init():715] updated telemetry
2025-05-14 00:10:52,466 INFO    MainThread:3658947 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2025-05-14 00:10:52,595 ERROR   MainThread:3658947 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-05-14 00:10:54,603 ERROR   MainThread:3658947 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/fdm/miniconda3/envs/evreal/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/home/fdm/miniconda3/envs/evreal/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-05-14 00:10:55,607 WARNING MsgRouterThr:3658947 [router.py:message_loop():77] message_loop has been closed
